# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-07-31 12:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='design',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
